RMDWEB/Controllers/UserRoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Data;
using System.Diagnostics;
using RMDWEB.Models;
using System.Runtime.Intrinsics.Arm;
using RMDWEB.Interface;
using RMDWEB.Impl;
using RMDWEB.Services.Interface;
using RMDWEB.Services.Impl;

namespace RMDWEB.Controllers
{
    [Authorize(Roles = "sys-admin")]
    public class UserRoleController : Controller
    {
        private readonly ILogger<UserRoleController> _logger;

        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly InterfaceSystemConfig _iConfig;
        private readonly InterfaceActivityLog _activitylog;
        private readonly InterfaceBank _ibank;
        private readonly InterfaceDepartment _idepartment;

        public UserRoleController(ILogger<UserRoleController> logger, UserManager<ApplicationUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _logger = logger;
            _iConfig = new RepoSystemConfig();
            _roleManager = roleManager;
            _userManager = userManager;
            _activitylog = new RepoActivityLog();
            _ibank = new RepoBank();
            _idepartment = new RepoDepartment();
        }



        public async Task<IActionResult> Index()
        {
            var users = await _userManager.Users.ToListAsync();
            //Add log for editing Banks
            ActivityLog log = new ActivityLog()
            {
                Activity = "UserRole/View Users",
                ActivityDate = DateTime.Now,
                UserName = User.Identity.Name,
                TableName = "Users",
                Detail = "View Users",
            };
            _activitylog.Add(log);
            return View(users.ToList());
        }

        private async Task<List<string>> GetUserRoles(ApplicationUser user)
        {
            return new List<string>(await _userManager.GetRolesAsync(user));
        }

        public async Task<IActionResult> Manage(string userId)
        {
            ViewBag.userId = userId;

            var user = new ApplicationUser();
            //check if role is user admin else other one
            user = _userManager.Users.Single(a => a.UserId.ToString() == userId);
            //var user = await _userManager.FindByIdAsync(userId);
            if (user == null)
            {
                ViewBag.ErrorMessage = $"User with Id = {userId} cannot be found";
                return View("NotFound");
            }
            else
            {
                ViewBag.UserName = user.UserName;
                var model = new List<ManageUserRolesViewModel>();
                foreach (var role in _roleManager.Roles)
                {
                    var userRolesViewModel = new ManageUserRolesViewModel
                    {
                        RoleId = role.Id,
                        RoleName = role.Name
                    };
                    if (await _userManager.IsInRoleAsync(user, role.Name))
                    {
                        userRolesViewModel.Selected = true;
                    }
                    else
                    {
                        userRolesViewModel.Selected = false;
                    }
                    model.Add(userRolesViewModel);
                }

                // Add log for editing Banks
                ActivityLog l = new ActivityLog()
                {
                    Activity = "UserRole/Manage Users",
                    ActivityDate = DateTime.Now,
                    UserName = User.Identity.Name,
                    TableName = "Users",
                    Detail = "View User Roles",
                };
                _activitylog.Add(l);

                return View(model);

            }

        }

        public IActionResult Details(int userId)
        {
            ApplicationUser u = _userManager.Users.Single(a => a.UserId == userId);

            if (u == null)
            {
                ViewBag.ErrorMessage = $"User with Id = {userId} cannot be found";
                return View("NotFound");
            }
            else
            {
                // Add log for editing Banks
                ActivityLog l = new ActivityLog()
                {
                    Activity = "UserRole/Users Details",
                    ActivityDate = DateTime.Now,
                    UserName = User.Identity.Name,
                    TableName = "Users",
                    Detail = "View User Details",
                };
                _activitylog.Add(l);
                return View(u);
            }

        }

        [HttpPost]
        public async Task<IActionResult> Manage(List<ManageUserRolesViewModel> model, string userId)
        {

            var user = _userManager.Users.Single(a => a.UserId.ToString() == userId);
            //var user = await _userManager.FindByIdAsync(userId);
            if (user == null)
            {
                return View();
            }
            var roles = await _userManager.GetRolesAsync(user);
            var result = await _userManager.RemoveFromRolesAsync(user, roles);
            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Cannot remove user existing roles");
                return View(model);
            }
            result = await _userManager.AddToRolesAsync(user, model.Where(x => x.Selected).Select(y => y.RoleName));
            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Cannot add selected roles to user");
                return View(model);
            }
            TempData["success"] = "User Role updated!";
            return RedirectToAction("Index");
        }


        public async Task<IActionResult> Edit(string id)
        {

            if (id == null || id == "")
            {
                ViewBag.ErrorMessage = $"User with Id = {id} cannot be found";
                return View("NotFound");
            }


            ApplicationUser u = new ApplicationUser();

            if (id != null && id != "")
            {
                u = await _userManager.FindByIdAsync(id);
                u.DepartmentTbl = _idepartment.singleDepartment(u.DepartmentId);
                u.StatusTbl = _iConfig.singelStatus(u.StatusId);

            }
            var dep = _iConfig.AllDepartments().Single(a => a.DepartmentId == u.DepartmentId);

            ViewBag.StatusId = new SelectList(_iConfig.AllStatus(), "StatusId", "Name", u.StatusId);
            ViewBag.DepartmentId = new SelectList(_iConfig.AllDepartments(), "DepartmentId", "Name", u.DepartmentId);
            ViewBag.BankId = new SelectList(_iConfig.AllBanks(), "BankId", "Name", dep.BankId);

            if (u == null)
            {
                ViewBag.ErrorMessage = $"User with Id = {id} cannot be found";
                return View("NotFound");
            }
            else
            {
                ViewBag.MSG = TempData["MSG"];
                return View(u);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ApplicationUser user)
        {
            var existingUser = await _userManager.FindByIdAsync(user.Id);

            if (existingUser == null)
            {
                // User not found
                return NotFound();
            }

            // Update the properties of the existing user
            existingUser.PhoneNumber = user.PhoneNumber;
            existingUser.FirstName = user.FirstName;
            existingUser.LastName = user.LastName;
            existingUser.FatherName = user.FatherName;
            existingUser.Email = user.Email;
            existingUser.UserId = user.UserId;
            existingUser.RegisterDate = user.RegisterDate;
            existingUser.PhoneNumberConfirmed=user.PhoneNumberConfirmed;
            existingUser.IpAddress=user.IpAddress;
            existingUser.ExpiryDate=user.ExpiryDate;
            existingUser.Designation=user.Designation;
            existingUser.PhoneNumber=user.PhoneNumber;
            existingUser.StatusId=user.StatusId;
            existingUser.DepartmentId=user.DepartmentId;
            existingUser.BankId=user.BankId;
           
            // Update other properties as needed

            // Save the changes
            var result = await _userManager.UpdateAsync(existingUser);

            if (result.Succeeded)
            {
                // Update successful
                TempData["success"] = "User updated successfully!";
                return RedirectToAction("Index");
            }
            else
            {
                // Failed to update user
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
               
                return View(user); // Show the edit view with validation errors
            }
        }


        public async Task<IdentityResult> ResetPasswordAsync(int UserId, string UserPassword)
        {
            var uID = _userManager.Users.Single(a => a.UserId == UserId).Id;
            ApplicationUser u = await _userManager.FindByIdAsync(uID);
            string token = await _userManager.GeneratePasswordResetTokenAsync(u);
            return await _userManager.ResetPasswordAsync(u, token, UserPassword);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public async Task<IActionResult> IndexRole()
        {
            var roles = await _roleManager.Roles.ToListAsync();
            return View(roles);

RMDWEB/Views/UserRole/Details.cshtml
@model ApplicationUser

@{
	ViewBag.Title = "User details";
	ViewBag.Active = "dab_users"; ;
}

<!-- start page title -->
<div class="row">
	<div class="col-12">
		<div class="page-title-box d-flex align-items-center justify-content-between">
			<div class="page-title">
				<h4 class="mb-0 font-size-18">User Details</h4>
				<ol class="breadcrumb">
					<li class="breadcrumb-item"><a asp-action="Index" asp-controller="Home">Home Page</a></li>
					<li class="breadcrumb-item"><a asp-action="Index" asp-controller="UserRole">Users</a></li>
					<li class="breadcrumb-item active">User Details</li>
				</ol>
			</div>
		</div>
	</div>
</div>
<!-- end page title -->

<div class="page-content-wrapper">
	<div class="row">
		<div class="col-12">
			<div class="card">
				<div class="card-body">
					<!-- Demo purpose only -->
					<div style="min-height: 200px;">
						<div class="row">
                            <div class="col-12">
                                <h3>User Details</h3>
                            </div>
                            <div class="col-12">
                                <hr/>
                            </div>
                        </div>
						<div class="row">
							<div class="col-12">
								<table class="table table-sm">
								<tr>
									<th width="20%">User ID</th>
									<td width="80%" class="pl-5">@Html.DisplayFor(model => model.UserId) </td>
								</tr>
								<tr>
									<th width="20%">Username</th>
									<td width="80%" class="pl-5">@Html.DisplayFor(model => model.UserName) </td>
								</tr>
								<tr>
									<th width="20%">Father Name</th>
									<td width="80%" class="pl-5">@Html.DisplayFor(model => model.FatherName) </td>
								</tr>
								<tr>
									<th width="20%">Email</th>
									<td width="80%" class="pl-5">@Html.DisplayFor(model => model.Email) </td>
								</tr>
								<tr>
									<th width="20%">Phone Number</th>
									<td width="80%" class="pl-5">@Html.DisplayFor(model => model.PhoneNumber) </td>
								</tr>
								<tr>
									<th width="20%">Expiry Date</th>
									<td width="80%" class="pl-5">@Html.DisplayFor(model => model.ExpiryDate) </td>
								</tr>
							</table>
							</div>
							<div class="col-12">
								<a asp-action="Index" class="btn btn-secondary w-lg mt-3">Back to List</a>
							</div>	
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- end page content-->

RMDWEB/Views/UserRole/DetailsRole.cshtml
@model Microsoft.AspNetCore.Identity.IdentityRole
@{
    ViewData["Title"]="Role Manager";
    ViewBag.Active="dab_roles";
}

<h2>Details.</h2>

<div>
    <h4>Roles.</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
</div>
<h4>List of users in this role</h4>
@if(ViewBag.UserCount==0)
{
    <hr />
    <p>No users found in this role.</p>
}

<table class="table">

    @foreach(var item in ViewBag.Users)
    {
        <tr>
            <td>
                @item.UserName
            </td>
        </tr>
    }
</table>
 

RMDWEB/Views/UserRole/Index.cshtml
@model IEnumerable<RMDWEB.Models.ApplicationUser>
@{
    ViewData["Title"]="Index";
    ViewBag.Active="users";
}

<!-- start page title -->
<div class="row">
    <div class="col-12">
        <div class="page-title-box d-flex align-items-center justify-content-between">
            <div class="page-title">
                <h4 class="mb-0 font-size-18">User</h4>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Home">Home Page</a></li>
                    <li class="breadcrumb-item active">Users</li>
                </ol>
            </div>
        </div>
    </div>
</div>
<!-- end page title -->

<!-- Start Page-content-Wrapper -->
<div class="page-content-wrapper">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-12 text-end">
                            <a href="/Identity/Account/Register" class="btn btn-primary mb-3" style="width:155px; letter-spacing:1px;"><i class="mdi mdi-plus"></i>User</a>
                        </div>
                    </div>
                    <table id="datatable" class="table table-sm table-bordered dt-responsive nowrap"
                           style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                        <thead>
                            <tr>
                                <th>
                                    <a asp-action="Index" asp-route-sortOrder="@ViewData["UserId"]">ID</a>
                                </th>
                                <th>
                                    <a asp-action="Index" asp-route-sortOrder="@ViewData["FirstName"]">Name</a>
                                </th>
                                <th>
                                    <a asp-action="Index" asp-route-sortOrder="@ViewData["LastName"]">Last Name</a>
                                </th>
                                <th>
                                    <a asp-action="Index" asp-route-sortOrder="@ViewData["Email"]">Email</a>
                                </th>
                                <th>
                                    <a asp-action="Index" asp-route-sortOrder="@ViewData["UserName"]">Username</a>
                                </th>


                                <th style="color:#20A6E8 !important">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var user in Model.OrderByDescending(a => a.UserId))
                {
                            <tr>
                                <td>@user.UserId</td>
                                <td>@user.FirstName</td>
                                <td>@user.LastName</td>
                                <td>@user.Email</td>
                                <td>@user.UserName</td>

                                <td>
                                        <a asp-controller="UserRole" asp-action="Manage" asp-route-userId="@user.UserId" class="btn btn-sm btn-floating">
                                            <i class="mdi mdi-cog text-primary" style="font-size:1.1rem"></i>
                                    </a>
                                        <a asp-controller="UserRole" asp-action="Details" asp-route-userId="@user.UserId" class="btn btn-sm btn-floating">
                                            <i class="mdi mdi-information text-primary" style="font-size:1.1rem"></i>
                                    </a>
                                        <a asp-controller="UserRole" asp-action="Edit" asp-route-id="@user.Id" class="btn btn-sm btn-floating">
                                            <i class="mdi mdi-pencil text-primary" style="font-size:1.1rem"></i>
                                    </a>

                                        <a onclick="changePassword(event,@user.UserId.Value)" class="btn btn-sm btn-floating">
                                            <i class="mdi mdi-lock text-primary" style="font-size:1.1rem"></i>
                                        </a>
                                </td>
                            </tr>
                }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <!-- end col -->
    </div>
</div>
<!-- End Page-content -->

<!-- Modal -->
<div class="modal fade" id="modal2" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Change Password</h5>
                <button onclick="closeModel()" type="button" class="btn-close" data-mdb-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">...</div>
            <div class="modal-footer">
                @*<button type="button" class="btn btn-secondary" data-mdb-dismiss="modal" onclick="closeModel('modal2')">Close</button>
                <button type="button" class="btn btn-primary" onclick="passConfigSubmit(${ id })" id="submitButtonId" name="submitButtonId">Save changes</button>*@
            </div>
        </div>
    </div>
</div>


@section css{
    <!-- DataTables -->
    <link href="~/assets/libs/datatables.net-bs4/css/dataTables.bootstrap4.min.css" rel="stylesheet" type="text/css" />
    <link href="~/assets/libs/datatables.net-buttons-bs4/css/buttons.bootstrap4.min.css" rel="stylesheet" type="text/css" />
    <!-- Responsive datatable examples -->
    <link href="~/assets/libs/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css" rel="stylesheet"
      type="text/css" />
    <link href="~/mdbootstrap/css/mdb.min.css" rel="stylesheet" />
}


@section Scripts{
    <!-- Required datatable js -->
    <script src="~/assets/libs/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="~/assets/libs/datatables.net-bs4/js/dataTables.bootstrap4.min.js"></script>
    <!-- Buttons examples -->
    <script src="~/assets/libs/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
    <script src="~/assets/libs/datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js"></script>
    <script src="~/assets/libs/jszip/jszip.min.js"></script>
    <script src="~/assets/libs/pdfmake/build/pdfmake.min.js"></script>
    <script src="~/assets/libs/pdfmake/build/vfs_fonts.js"></script>
    <script src="~/assets/libs/datatables.net-buttons/js/buttons.html5.min.js"></script>
    <script src="~/assets/libs/datatables.net-buttons/js/buttons.print.min.js"></script>
    <script src="~/assets/libs/datatables.net-buttons/js/buttons.colVis.min.js"></script>
    <!-- Responsive examples -->
    <script src="~/assets/libs/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/assets/libs/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js"></script>
    <!-- Datatable init js -->
    <script src="~/assets/js/pages/datatables.init.js"></script>
    <script src="~/mdbootstrap/js/mdb.min.js"></script>
}

<script>

    $('select').addClass('browser-default select-min-width');
    var select = $('select').selectize({
        create: false,
        sortField: "text",
    })


    function passwordChange(id) {
        if (confirm('Are you sure')) {
            $("#fullPageLoading").show()
            var passwordId = document.getElementById("passwordId").value;
            var userPassChangeId = document.getElementById("userPassChangeId").value;

            $.ajax({
                url: '/api/SysConfiguration/changePasswordOfUser?UserId=' + userPassChangeId + '&Password=' + passwordId,
                method: 'POST',
                success: (response) => {
                    $("#fullPageLoading").hide()
                    M.toast({ html: response, classes: 'bg-red-500 rounded-xl' })
                    closeModel("modal1");
                },
                error: () => {
                    $("#fullPageLoading").hide()
                    M.toast({ html: 'Something went wrong', classes: 'bg-red-500 rounded-xl' })
                }
            })
        }
    }


    function changePassword(element, id) {
        let html = `<p><i class="ri-arrow-right-s-fill"></i>Password should be at least 8 characters long</p>`
        html += `<p><i class="ri-arrow-right-s-fill"></i>Password should contain at least one capital letter and one symbol</p>`
        html += `<br/>Example:<span class="text-danger mb-2"> Abc@123</span>`
        html += `<input  type="hidden" id="userPassChangeId" value="${id}" />`
        html += `<br/><label>New Password</label>`
        html += `<input class="form-control" type="password" name="password" id="passwordId" onchange="passwordIdChange()"/><span id="passwordIdError"></span>`
        html += `<br/><label>Confirm New Password</label>`
        html += `<input class="form-control mb-2" type="password" name="confirmPassword" id="confirmPasswordId" onchange="passwordIdChange()"/><span id="confirmPasswordIdError"></span>`
        html += `<button onclick="passwordChange(${id})" class="btn btn-primary m-2" id="submitButtonId" name="submitButtonId">Save Changes</button>`
        html += `<button class="btn btn-secondary text-center" onclick="closeModel()">Close</button>`
        $('.modal-body').html(html);
        $('#modal2').modal('toggle')
        //document.getElementById( "submitButtonId" ).style.display = "none";
    }

    function passwordIdChange() {
        document.getElementById("submitButtonId").style.display = "none";
        var pw = document.getElementById("passwordId").value;
        var pw2 = document.getElementById("confirmPasswordId").value;
        if (pw.length < 8 || pw.length > 15) {
            document.getElementById("passwordIdError").textContent = "The password must be more than 8 and less than 15 characters.";
        } else {

            var passw = /^(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,15}$/;
            if (pw.match(passw)) {
                document.getElementById("passwordIdError").textContent = "The password is correct.";
                if (pw == pw2) {
                    document.getElementById("confirmPasswordIdError").textContent = "The password has matched."
                    document.getElementById("submitButtonId").style.display = "block";
                } else {
                    document.getElementById("confirmPasswordIdError").textContent = "The repeat password must be the same as the entered password.";
                }
            } else {
                document.getElementById("passwordIdError").textContent = "It must contain at least one uppercase and lowercase letter.";
            }
        }
    }

    function closeModel() {
        $('#modal2').modal('hide')
    }

</script>

RMDWEB/Views/UserRole/IndexRole.cshtml
@model List<Microsoft.AspNetCore.Identity.IdentityRole>


@{
    ViewData["Title"]="Role Manager";
    ViewBag.Active="dab_roles";
}
<h1>Role Manager</h1>
<form method="post" asp-action="AddRole" asp-controller="UserRole">
    <div class="input-group">
        <input name="roleName" class="form-control w-25">
        <span class="input-group-btn">
            <button class="btn btn-info">Add New Role</button>
        </span>
    </div>
</form>
<table id="example" class="display table nowrap compact " style="width:100%">
    <thead>
        <tr>
            <th>Role</th>
            <th>Title</th>
            <th>change</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var role in Model.OrderBy(a => a.Name))
        {
            <tr>
                <td>@role.Name</td>
                <td>@role.Id</td>
                <td><i class="material-icons">info</i></td>
            </tr>
        }
    </tbody>
</table>

@section css{
    @Html.Partial("_Datatable", new ViewDataDictionary(ViewData) { { "type", "css" }, { "buttons", "true" }})

}

    @section js{
    @Html.Partial("_Datatable", new ViewDataDictionary(ViewData) {{ "type", "js" }, { "buttons", "true" }})

}

RMDWEB/Views/UserRole/Manage.cshtml
@model List<ManageUserRolesViewModel>
@{
    ViewData["Title"]="Manage";
    ViewBag.Active="dab_users";
}

<!-- start page title -->
<div class="row">
    <div class="col-12">
        <div class="page-title-box d-flex align-items-center justify-content-between">
            <div class="page-title">
                <h4 class="mb-0 font-size-18">Manage Roles</h4>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Home">Home Page</a></li>
                    <li class="breadcrumb-item"><a asp-action="Index" asp-controller="UserRole">Users</a></li>
                    <li class="breadcrumb-item active">Manage Roles</li>
                </ol>
            </div>
        </div>
    </div>
</div>
<!-- end page title -->

<div class="page-content-wrapper">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <!-- Demo purpose only -->
                    <div style="min-height: 300px;">
                        <div class="row">
                            <div class="col-12">
                                <h3>Manage Roles</h3>
                            </div>
                            <div class="col-12">
                                <hr/>
                            </div>
                        </div>
                        <form method="post" class="row">
                            @for (int i = 0; i < Model.Count; i++)
                            {
                                <div class="col-12" style="text-align:left">
                                    <input type="hidden" asp-for="@Model[i].RoleId" />
                                    <input type="hidden" asp-for="@Model[i].RoleName" />
                                    <input asp-for="@Model[i].Selected" class="form-check-input" />
                                    <label class="form-check-label" asp-for="@Model[i].Selected">
                                        @Model[i].RoleName
                                    </label>
                                </div>
                            }
                            <div asp-validation-summary="All" class="text-danger"></div>
                            <div class="col s12">
                                <input type="submit" value="Update" class="btn btn-primary w-lg" />
                                <a asp-action="Index" class="btn btn-secondary w-lg">Back to List</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- end page content-->